### ISSUE TITLE
Error when compile with gcc 5.4

### ISSUE THREAD

**Issue by xichuang** [m-reuter/arpackpp#6]
Hello

After successfully configuring with cmake ../, 
The following errors occur during the compilation step

/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xb2): undefined reference to`signbitq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xbf): undefined reference to`finiteq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x133): undefined reference to`quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x254): undefined reference to`finiteq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xaff): undefined reference to`isnanq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xb83): undefined reference to`quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xf7d): undefined reference to`quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x10d8): undefined reference to`quadmath_snprintf'

I'm using ubuntu  16.04 with gcc 5.4. 
I think the -lquadmath should be added to the link flags.

**Comment by monajalal** [comment]
I added that flag but I still get the same error:

```
multithread:
        $(CC) -g $(CFLAGS) mmglm_spd_multithread.cpp -o ../bin/mmglm_spd_par -fopenmp -lquadmath -O3 $(LIB_PATH) $(INC_PATH)'
```

error is:

```
jalal@klein:~/computer_vision/mmglm_neuroimage_private-master/lib/c++/src$ make
g++ -g -Wall -Wextra -Wunreachable-code -static mmglm_spd_multithread.cpp -o ../bin/mmglm_spd_par -fopenmp -lquadmath -O3 -llapack -lblas -lpthread -lgfortran  -lboost_system -lboost_filesystem -I ../lib/armadillo-3.930.2/include/
mmglm_spd_multithread.cpp: In function ‘int main(int, char**)’:
mmglm_spd_multithread.cpp:117:10: warning: unused variable ‘length’ [-Wunused-variable]
   size_t length=0;//initializing length as a counter
          ^
/usr/lib/gcc/x86_64-linux-gnu/5/libgomp.a(target.o): In function `gomp_target_init':
(.text+0xba): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xb2): undefined reference to `signbitq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xbf): undefined reference to `finiteq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x133): undefined reference to `quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x254): undefined reference to `finiteq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xaff): undefined reference to `isnanq'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xb83): undefined reference to `quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0xf7d): undefined reference to `quadmath_snprintf'
/usr/lib/gcc/x86_64-linux-gnu/5/libgfortran.a(write.o): In function `write_float':
(.text.write_float+0x10d8): undefined reference to `quadmath_snprintf'
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'multithread' failed
make: *** [multithread] Error 1
```

**Comment by m-reuter** [comment]
Try adding -lquadmath after $(LIB_PATH), could be a problem of ordering.

**Comment by monajalal** [comment]
@m-reuter dear professor Reuter, I solved it like this http://stackoverflow.com/questions/39730418/text-write-float0xf7d-undefined-reference-to-quadmath-snprintf

**Comment by m-reuter** [comment]
@xichuang Here we can simply move this
`find_library(QUADMATH_LIB quadmath PATHS ${GFORTRAN_PATH})`
a few lines up, outside the IF (APPLE) block. That should fix it, let me know and I can make that change (or generate a pull request). I currently don't have Ubuntu 16.04 to test this.
